Add New Benchmarks
risc0/risc0 pull request #1842
Opened 2024-05-16 19:15 UTC by morgangibbs87

- [ ] g4dn.xlarge
- [ ] L4
- [ ] c7i.48xlarge to `nightly`?

2024-05-17 00:56 UTC, flaub commented on .github/workflows/bench_pr.yml
> +            device: nvidia_rtx_l4
this should be named the AWS instance type

2024-05-17 00:58 UTC, flaub commented
I don't think we need `c7i.48xlarge`. Also we should rename L4 to the AWS instance type = `g6.xlarge`

2024-05-17 20:04 UTC, flaub requested changes
Holding off for now

2024-06-13 21:46 UTC, morgangibbs87 commented
Closing this PR to split into separate tests.

2024-06-13 21:46 UTC, closed without merging