Nahoc/no cache2
risc0/risc0 pull request #1940
Opened 2024-06-07 11:46 UTC by nahoc

2024-06-14 18:55 UTC, morgangibbs87 approved these changes

2024-06-14 19:05 UTC, flaub commented
How long do you think before the rc/beta becomes released? I'd like to avoid using pre-released dependencies if possible.

2024-06-21 00:43 UTC, flaub requested changes
Holding off for now, hoping we can wait until these deps are stable.

2024-09-09 17:37 UTC, nahoc commented
so Nextjs v15 is now in RC:
https://nextjs.org/blog/next-15-rc

I think it's safe to merge this PR now, which improves caching logic and other nits.

2024-09-09 17:52 UTC, nahoc commented
also the email for key requested has `key` but the other one has `Key`, should be consistent 
<img width="287" alt="image" src="https://github.com/user-attachments/assets/1d19b7bc-227b-4d6e-b0c3-16e5014934ad">

2024-09-20 01:28 UTC, pdg744 approved these changes
If it meets Morgan's standards, LGTM :) 
Thank you!

2024-09-20 04:14 UTC, flaub requested changes
We should avoid using non-released software, especially for mission critical sites.

2024-09-20 13:43 UTC, nahoc commented on web/package.json
> +    "react-dom": "19.0.0-rc-e210d081-20240909",
for Next15 to work, yes
`$ unhandledRejection Error: Next.js requires react >= 19.0.0 to be installed.`
react 19 should be released very soon, but no clear date :/ 

2024-11-19 17:59 UTC, nahoc commented
@flaub this PR has been open for around 5 months now, do you think it's stable enough to merge? I got a few other improvements depending on it. 🙏

2024-11-19 19:01 UTC, flaub commented
If we can drop the `-rc` dependencies then I'll approve.

2024-11-19 19:13 UTC, nahoc commented
> If we can drop the `-rc` dependencies then I'll approve.

OK, just downgraded to React v18 for the time being. 👍

2024-11-19 19:53 UTC, flaub approved these changes

2024-11-19 19:59 UTC, merged