feat(reports): add copy to benchmarks
risc0/risc0 pull request #2366
Opened 2024-09-23 17:40 UTC by nahoc

<img width="550" alt="image" src="https://github.com/user-attachments/assets/bda25801-9b47-45e9-a74f-688635d98a6e">

also updated fonts in regards to https://linear.app/risczero/issue/WEBR0-25/text-formatting-bug-on-zkvm-design-blogpost

2024-09-23 21:10 UTC, pdg744 approved these changes
Thank you!

Tagging in @flaub in case he has feedback about how we handle this verbiage/pointers.

2024-09-25 18:39 UTC, flaub requested changes
The `benchmarks` directory is only involved with the Application Benchmarks page. I'm also not sure we should link to the source code because it can change over time.

2024-09-27 15:37 UTC, pdg744 commented
> I'm also not sure we should link to the source code because it can change over time.
Hmm I hear you, but it feels pretty essential to me that users (on our team and externally) can make meaning of the reports, and it seems to me that adding a link to the source code is the most straight-forward path to addressing that issue. I think the maintenance cost is worth the benefit, but definitely open to other solutions if you have suggestions for a better way to address the problem of "what do these reports mean?"

2024-09-27 15:45 UTC, pdg744 commented
> The benchmarks directory is only involved with the Application Benchmarks page.

good catch... some notes below on the 4 status of the 4 reports, in my eyes: 

- crates validation page is good as is; i don't think users will struggle to make meaning of that info. 
- datasheet page is good as is; there's already a pointer to the recursive proving architecture page and an "example" at the top of the page
- application benchmarks & benchmarks are currently very opaque to interpret. 
  - `Application Benchmarks` would be clarified by a pointer to `risc0/benchmarks`
  - For `Benchmarks`, I guess I don't actually what to point users to in order to clarify meaning here. I guess we could just include a link to the [Recursion page on dev docs](https://dev.risczero.com/api/recursion) and call that sufficient.

2024-11-13 01:54 UTC, pdg744 approved these changes

2024-11-13 01:56 UTC, pdg744 requested changes
Whoops -- hit "approve" but it looks like there are some suggestions above that haven't been incorporated yet.

2025-04-28 09:36 UTC, closed without merging