`rzup`: Add `list` command for listing installed and available toolchains and extensions
risc0/risc0 pull request #2409
Opened 2024-10-09 10:25 UTC by matthiasgeihs

This PR proposes to add a `list` command to `rzup` for listing installed and available toolchains and extensions.

Closes #2316.

2025-02-11 01:57 UTC, bobbobbio requested changes
This PR is unfortunately extremely out-of-date now. We have completely re-written `rzup`, and I don't think we had this work on our radar. 

Sorry about that.

These changes have to be rebased and probably drastically rewritten in a way that works with the current state of the code.

2025-02-11 07:51 UTC, SchmErik commented
closing for the timebeing - please feel free to reopen when rebased and rewritten to fit the current rzup

2025-02-11 07:51 UTC, closed without merging

2025-02-11 08:12 UTC, matthiasgeihs commented
are you actually interested in including this feature?

2025-02-13 21:15 UTC, bobbobbio commented
Hey @matthiasgeihs , yes we are interested in including this feature, it is something other people have requested.

If you want to keep working on this we would grateful to have your hard work, if not thats okay we should get to eventually ourselves. If you need some guidance feel free to reach out to me on discord. Thanks!