Override gcc version
risc0/risc0 pull request #2576
Opened 2024-11-30 19:44 UTC by saefstroem

Closes #2575 
Closes ZKVM-736

This allows the user to specify `NVCC_CCBIN` and override the default gcc compiler that is used by the nvcc compiler as the cc build tool does not adhere to if this variable is simply set from the linux environment.

2024-12-01 11:13 UTC, saefstroem commented
@flaub

2025-01-14 19:45 UTC, flaub commented
Related: #2695

2025-01-14 20:20 UTC, saefstroem commented
> Possibly duplicate: #2695 

That is the duplicate. This PR is 2mo old :)

2025-01-14 20:23 UTC, flaub commented
Are they both trying to do the same thing?

2025-01-14 20:31 UTC, saefstroem commented
> Are they both trying to do the same thing?

Yes but this PR allows the specification of the native Nvidia env variables instead of creating custom logic. This is a one-line fix.

2025-01-15 01:51 UTC, flaub approved these changes

2025-01-16 03:20 UTC, flaub requested changes

2025-01-16 03:20 UTC, flaub commented on risc0/build_kernel/src/lib.rs
> +            .ccbin(false)
This seems to break in our CI environment. Is there a way we can make this conditional? Perhaps only if `NVCC_CCBIN` is defined?

2025-01-16 10:14 UTC, saefstroem commented on risc0/build_kernel/src/lib.rs
> +            .ccbin(false)
This is a good idea. I'll update it to only disable if that env var is defined.

2025-01-16 18:23 UTC, saefstroem commented
@flaub

2025-01-16 19:00 UTC, flaub commented on risc0/build_kernel/src/lib.rs
> -            .debug(false)
How about this?

```
build
    .cuda(true)
    .cudart(&cudart)
    .debug(false)
    .ccbin(!env::var("NVCC_CCBIN").is_ok())
```

2025-01-17 00:02 UTC, saefstroem commented
@flaub Good suggestion, simplified even further :)

2025-01-17 00:22 UTC, flaub commented
Almost there, can you bump the first line so it reads:
```
// Copyright 2025 RISC Zero, Inc.
```

2025-01-17 10:12 UTC, saefstroem commented
> Almost there, can you bump the first line so it reads:
> 
> ```
> // Copyright 2025 RISC Zero, Inc.
> ```

done :)

2025-01-21 22:00 UTC, flaub approved these changes

2025-01-21 22:41 UTC, merged