Update README.md
risc0/risc0 pull request #88
Opened 2022-05-06 18:31 UTC by pdg744

fixed link to http://www.risczero.com on battleship readme

2022-05-06 18:36 UTC, flaub requested changes

2022-05-06 18:36 UTC, flaub commented on examples/rust/battleship/README.md
> +*This README includes instructions to install and play RISC Zero Battleship on your own machine. For more information about RISC Zero Battleship, check out the tutorials at [www.risczero.com](http://
Use `https://` link

2022-05-06 20:02 UTC, choongng approved these changes
Approve with HTTPS change

2022-05-10 21:44 UTC, flaub commented
Should be fixed in #95

2022-05-10 21:44 UTC, closed without merging