Accept JSON as payload for relay 's /v1/callbacks
risc0/risc0 pull request #948
Opened 2023-10-04 16:24 UTC by DefiCake

Closes #939

2023-10-04 19:57 UTC, mothran commented
Approved for CI and added some reviewers who can help you out.

2023-10-05 13:16 UTC, capossele commented on bonsai/ethereum-relay/src/api/bincode.rs
> +                "Expected request with `Content-Type: application/octet-stream`",
```suggestion
                "Expected request with `Content-Type: application/octet-stream` or `Content-Type: application/json`",
```

2023-10-05 13:19 UTC, capossele commented on bonsai/ethereum-relay/src/api/bincode.rs
> +        S: Send + Sync,
```suggestion
where
    T: DeserializeOwned,
    B: HttpBody + Send + 'static,
    B::Data: Send,
    B::Error: std::error::Error + Send + Sync,
    S: Send + Sync,
```

2023-10-05 13:35 UTC, capossele requested changes
Thanks for that!
Overall it's a nice addition. I have one observation:
The `Bincode` extractor is now mixed with json. I'd suggest to rename it to something more neutral that works for json as well. Same goes for the its documentation.
Another plus would be to have a test in place that make sure both bincode and json encoding deserialise correctly to a `CallbackRequest`.

2023-10-05 19:27 UTC, nategraf reviewed
Looks good! Similar to @caposselemy only comment is to rename the file and type to reflect the new more general usage 👍 Thanks for getting involved!

2023-10-06 10:29 UTC, DefiCake commented
I think the CI is failing due to the last commit in main branch

2023-10-06 10:32 UTC, capossele commented
but yeah, the rest of the tests are failing for some other reason. We'll sort that out

2023-10-06 10:57 UTC, DefiCake commented
@capossele fmt run, I 'll await to update wit hthe main branch

2023-10-06 14:47 UTC, capossele approved these changes
Awesome, thanks!

2023-10-06 15:32 UTC, merged